#!/bin/bash

if [[ "$reason" == "BOUND" || "$reason" == "RENEW" || "$reason" == "REBIND" || "$reason" == "REBOOT" ]]; then
	if ! ip r | grep -q "default.*$interface"; then
		ip r add default via "$new_routers" dev "$interface" metric "1"
	fi
fi
