# configure zsh
unsetopt autocd
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion::complete:*' gain-privileges 1
zmodload zsh/complist
bindkey -M menuselect '^[[Z' reverse-menu-complete
export WORDCHARS=''
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
bindkey -e

HISTFILE=~/.config/zsh/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY

PS1="%B%F{yellow}%n %(?.%F{green}.%F{red})➜ %F{blue}%1~ %b%F{white}"

export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:'
alias ls="ls --color=auto"

# zsh-autosuggestions plugin
source /home/$USER/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# vim plugin (https://github.com/softmoth/zsh-vim-mode)
source /home/$USER/.config/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# bindkey -M viins ',c' vi-cmd-mode

#lfcd
lf() {
    tmp="$(mktemp)"
    /bin/lf -last-dir-path="$tmp" "$@" 
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}

# others
swap()         
{
    local TMPFILE=tmp.$$
    sudo mv "$1" $TMPFILE && sudo mv "$2" "$1" && sudo mv $TMPFILE "$2"
}

ipinfo() {
    curl http://ip-api.com/$1
}

route() {

	name=$(nmcli c | grep -vE 'NAME|lo' | awk -F '  ' 'NR==1 {print $1}')
	gateway=$(nmcli connection show "$name" | grep IP4.GATEWAY | awk '{print $2}')

	if [[ -z "$2" ]] ; then
		echo "You didn't enter the required ip address!" ; return 
	fi

	case $1 in

		add)
			nmcli connection modify "$name" +ipv4.routes "$2 $gateway"
		;;

		remove)
			nmcli connection modify "$name" -ipv4.routes "$2 $gateway"
		;;

		*)
			echo "There is no operation $1, choose between either add/remove" ; return
		;;

	esac

	nmcli connection up "$name"

	echo "$name Updated successfully"

}

feh() {
	/usr/bin/feh --keep-zoom-vp -g 1600x900 "$@"
}

dns() {

	case $1 in

		default)
			echo -e \# Generated by NetworkManager \\nnameserver 1.1.1.1 \\nnameserver 8.8.8.8 | sudo tee /etc/resolv.conf
		;;

		electro)
			echo -e \# Generated by ye iranie badbakht \\nnameserver 78.157.42.100 \\nnameserver 78.157.42.101 | sudo tee /etc/resolv.conf
		;;

		shecan)
			echo -e \# Generated by ye iranie badbakht \\nnameserver 178.22.122.100 \\nnameserver 185.51.200.2 | sudo tee /etc/resolv.conf
		;;

		*)
			echo "There is no operation $1, choose between either default/electro/shecan" ; return
		;;

	esac

	echo "DNS Updated successfully"

}

chains () {
	for chain in 1 2 3 4 5 6 7 8 9 10 11; do
		echo -e $chain 👇
		ping -c 1 -W 0.1 c$chain.aghamanjal.com | awk 'NR==1{gsub(/\(|\)/,"",$3);print $3 "\n"}'
	done
}
