#! /bin/sh

# priority startup -------------------------------------------------------------------------------------------------------------------------------------------------

export PATH="$PATH:/home/murphy/.local/bin"
export PATH="$PATH:/usr/bin/eww"
fehbg &
picom -b
pgrep -x eww > /dev/null || eww open-many actions spotify info dates > /dev/null 2>&1 && eww reload && init_eww &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xrandr --output DP-4 --mode 1920x1080 --rate 240 &
nvidia-settings -l &
pgrep -x ChatterBlocker > /dev/null || ChatterBlocker /dev/input/by-id/usb-Logitech_G513_Carbon_Tactile_0B5238613437-event-kbd 30 2>&1 &

# end of priority startup ------------------------------------------------------------------------------------------------------------------------------------------



# bspwm config -----------------------------------------------------------------------------------------------------------------------------------------------------

bspc monitor DP-4 -d 1 2 3 &
bspc monitor HDMI-0 -d 4 5 6 &
bspc config border_width 0 &
bspc config window_gap 15 &
bspc config split_ratio 0.50 &

# end of bspwm config ----------------------------------------------------------------------------------------------------------------------------------------------



#startup -----------------------------------------------------------------------------------------------------------------------------------------------------------

vpn on
xset q | grep -o "Num Lock:    on" || xdotool key Num_Lock &
setxkbmap -layout us,ir -option 'grp:win_space_toggle' &
imwheel -b "45" -k
pkill openrgb ; openrgb -p blue &
light-locker --late-locking --lock-after-screensaver=0 &
pkill fullscreenrc ; fullscreenrc &
pactl list | grep "Name: FilteredMic" > /dev/null || pactl load-module module-echo-cancel use_master_format=1 aec_method="webrtc" aec_args="analog_gain_control=1 agc_start_volume=0 noise_suppression=1" source_name="FilteredMic"
pactl list | grep "Name: IOMix" > /dev/null || pactl load-module module-null-sink sink_name="IOMix"
pactl list | grep "Mix input" > /dev/null || pactl load-module module-loopback source="FilteredMic" sink="IOMix" "Mix input"
pactl list | grep "Mix output" > /dev/null || pactl load-module module-loopback source="alsa_output.pci-0000_00_1f.3.analog-stereo.monitor" sink="IOMix" "Mix output"
pgrep -x gpu-screen-reco > /dev/null || gpu-screen-recorder -w "DP-4" -q "ultra" -f 60 -a "IOMix.monitor" -r 90 -c "mp4" -o /mnt/Murphy/Media/Records > /dev/null 2>&1 &

#end of startup ----------------------------------------------------------------------------------------------------------------------------------------------------
