#!/bin/bash

# Bspwm config -----------------------------------------------------------------------------------------------------------------------------------------------------

bspc monitor DP-4 -d 1 2 3 &
bspc monitor HDMI-0 -d 4 5 6 &
bspc config border_width 0 &
bspc config window_gap 15 &
bspc config pointer_motion_interval 0 &
bspc config external_rules_command /home/murphy/DotFiles/StarryNight/home/murphy/.config/bspwm/rules &

# End of bspwm config ----------------------------------------------------------------------------------------------------------------------------------------------



# Priority startup -------------------------------------------------------------------------------------------------------------------------------------------------

fehbg &
xsetroot -cursor_name left_ptr &
xrandr --output DP-4 --mode 1920x1080 --rate 240 &
picom -b
pgrep -x eww > /dev/null || eww open-many actions spotify info dates &> /dev/null && init_eww &
pgrep -x ChatterBlocker > /dev/null || ChatterBlocker /dev/input/by-id/usb-Logitech_G513_Carbon_Tactile_0B5238613437-event-kbd 40 > /dev/null &
pgrep -x sxhkd > /dev/null || sxhkd &
nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings -l &

# End of priority startup ------------------------------------------------------------------------------------------------------------------------------------------



# Startup -----------------------------------------------------------------------------------------------------------------------------------------------------------

pkill openrgb ; openrgb -p blue > /dev/null &
vpn on > /dev/null &
xset q | grep -o "Num Lock:    on" || xdotool key Num_Lock &
imwheel -b "45" -k &> /dev/null
pgrep -x ClipGuard > /dev/null || ClipGuard > /dev/null &
pkill fullscreenrc ; fullscreenrc > /dev/null &
light-locker --late-locking --lock-after-screensaver=0 &
pactl list | grep "Name: FilteredMic" > /dev/null || pactl load-module module-echo-cancel use_master_format=1 aec_method="webrtc" aec_args="noise_suppression=1" source_name="FilteredMic"
pactl list | grep "Name: IOMix" > /dev/null || pactl load-module module-null-sink sink_name="IOMix"
pactl list | grep "Mix input" > /dev/null || pactl load-module module-loopback source="FilteredMic" sink="IOMix" "Mix input"
pactl list | grep "Mix output" > /dev/null || pactl load-module module-loopback source="alsa_output.pci-0000_00_1f.3.analog-stereo.monitor" sink="IOMix" "Mix output"
sleep 1 ; pgrep -x gpu-screen-reco > /dev/null || gpu-screen-recorder -w "DP-4" -q "ultra" -f 60 -a "IOMix.monitor" -r 90 -c "mp4" -o /mnt/Murphy/Media/Records -v no > /dev/null &

# End of startup ----------------------------------------------------------------------------------------------------------------------------------------------------
